In [1]:
import netCDF4 as nc
from netCDF4 import num2date,date2index
import datetime
import csv
import numpy as np
import pandas as pd
import xarray as xr
import tensorflow as tf
from tensorflow import keras
from keras.layers import Input, Dense
from keras.models import Model
from sklearn.preprocessing import normalize
import seaborn as sns
from sklearn.feature_selection import mutual_info_regression

In [2]:
data = nc.Dataset('sst.nc')

In [3]:
data

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    CDI: Climate Data Interface version 1.9.10 (https://mpimet.mpg.de/cdi)
    source: NOAA/NESDIS/National Climatic Data Center
    institution: NOAA/NESDIS/National Climatic Data Center
    Conventions: CF-1.0
    title: NOAA Extended Reconstructed SST V3b
    comments: The extended reconstructed sea surface temperature (ERSST)
was constructed using the most recently available
Comprehensive Ocean-Atmosphere Data Set (COADS) SST data
and improved statistical methods that allow stable
reconstruction using sparse data.
Currently, ERSST version 2 (ERSST.v2) and version 3 (ERSST.v3) and ERSST.v3b) are available from NCDC.
ERSST.v3b is an improved extended reconstruction over version 2.
 but with no satellite data
    platform: Model
    citation: Smith, T.M., R.W. Reynolds, Thomas C. Peterson, and Jay Lawrimore 2007: Improvements to NOAA's Historical Merged Land-Ocean Surface Temperature Analysis (1880-2006). In press. Journal of Climate (ERSSTV3).
Smith, T.M., and R.W. Reynolds, 2003: Extended Reconstruction of Global Sea Surface Temperatures Based on COADS Data (1854-1997). Journal of Climate, 16, 1495-1510. ERSSTV1
 Smith, T.M., and R.W. Reynolds, 2004: Improved Extended Reconstruction of SST (1854-1997). Journal of Climate, 17, 2466-2477.
    dataset_title: Extended Reconstructed Sea Surface Temperature (ERSST)
    source_doc: https://www.ncdc.noaa.gov/data-access/marineocean-data/extended-reconstructed-sea-surface-temperature-ersst-v3b
    data_modified: 2020-03-03
    References: https://www.psl.noaa.gov/data/gridded/data.noaa.ersst.html
    CDO: Climate Data Operators version 1.9.10 (https://mpimet.mpg.de/cdo)
    history: 15-Jun-2023 02:17:17 Subset NOAA/PSL
    dimensions(sizes): time(708), lon(180), lat(89)
    variables(dimensions): float64 time(time), float32 lon(lon), float32 lat(lat), float32 sst(time, lat, lon)
    groups:

In [4]:
sst = data.variables['sst']
print(sst)

<class 'netCDF4._netCDF4.Variable'>
float32 sst(time, lat, lon)
    long_name: Monthly Means of Sea Surface Temperature
    units: degC
    _FillValue: -9.96921e+36
    missing_value: -9.96921e+36
    precision: 2
    least_significant_digit: 1
    var_desc: Sea Surface Temperature
    dataset: NOAA Extended Reconstructed SST V3b
    level_desc: Surface
    statistic: Mean
    parent_stat: Mean
    actual_range: [-1.8  33.95]
unlimited dimensions: time
current shape = (708, 89, 180)
filling off

In [5]:
sst[:]

masked_array(
  data=[[[-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        ...,

        [[-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         [-1.7999999523162842, -1.7999999523162842, -1.7999999523162842,
          ..., -1.7999999523162842, -1.7999999523162842,
          -1.7999999523162842],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[-1.75, -1.75, -1.7400000095367432, ..., -1.7599999904632568,
          -1.7599999904632568, -1.75],
         [-1.690000057220459, -1.690000057220459, -1.6699999570846558,
          ..., -1.7599999904632568, -1.7300000190734863,
          -1.7100000381469727],
         [-1.7300000190734863, -1.690000057220459, -1.6699999570846558,
          ..., -1.7999999523162842, -1.7799999713897705,
          -1.7599999904632568],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]],

        [[-1.7799999713897705, -1.7699999809265137, -1.7699999809265137,
          ..., -1.7799999713897705, -1.7799999713897705,
          -1.7799999713897705],
         [-1.75, -1.75, -1.75, ..., -1.7699999809265137,
          -1.7599999904632568, -1.75],
         [-1.7400000095367432, -1.7300000190734863, -1.7300000190734863,
          ..., -1.7799999713897705, -1.7599999904632568, -1.75],
         ...,
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --],
         [--, --, --, ..., --, --, --]]],
  mask=[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        ...,

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True],
         [ True,  True,  True, ...,  True,  True,  True]]],
  fill_value=-9.96921e+36,
  dtype=float32)

In [6]:
np.max(sst)

33.95

In [8]:
np.min(sst)

-9.96921e+36

In [9]:
latitude = data.variables['lat']
print(latitude)

<class 'netCDF4._netCDF4.Variable'>
float32 lat(lat)
    standard_name: latitude
    long_name: Latitude
    units: degrees_north
    axis: Y
    actual_range: [ 88. -88.]
unlimited dimensions:
current shape = (89,)
filling off

In [10]:
latitude[:]

masked_array(data=[ 88.,  86.,  84.,  82.,  80.,  78.,  76.,  74.,  72.,
                    70.,  68.,  66.,  64.,  62.,  60.,  58.,  56.,  54.,
                    52.,  50.,  48.,  46.,  44.,  42.,  40.,  38.,  36.,
                    34.,  32.,  30.,  28.,  26.,  24.,  22.,  20.,  18.,
                    16.,  14.,  12.,  10.,   8.,   6.,   4.,   2.,   0.,
                    -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18.,
                   -20., -22., -24., -26., -28., -30., -32., -34., -36.,
                   -38., -40., -42., -44., -46., -48., -50., -52., -54.,
                   -56., -58., -60., -62., -64., -66., -68., -70., -72.,
                   -74., -76., -78., -80., -82., -84., -86., -88.],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [11]:
longitude = data.variables['lon']
print(longitude)

<class 'netCDF4._netCDF4.Variable'>
float32 lon(lon)
    standard_name: longitude
    long_name: Longitude
    units: degrees_east
    axis: X
    actual_range: [  0. 358.]
unlimited dimensions:
current shape = (180,)
filling off

In [12]:
longitude[:]

masked_array(data=[  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,
                    18.,  20.,  22.,  24.,  26.,  28.,  30.,  32.,  34.,
                    36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
                    54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
                    72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,
                    90.,  92.,  94.,  96.,  98., 100., 102., 104., 106.,
                   108., 110., 112., 114., 116., 118., 120., 122., 124.,
                   126., 128., 130., 132., 134., 136., 138., 140., 142.,
                   144., 146., 148., 150., 152., 154., 156., 158., 160.,
                   162., 164., 166., 168., 170., 172., 174., 176., 178.,
                   180., 182., 184., 186., 188., 190., 192., 194., 196.,
                   198., 200., 202., 204., 206., 208., 210., 212., 214.,
                   216., 218., 220., 222., 224., 226., 228., 230., 232.,
                   234., 236., 238., 240., 242., 244., 246., 248., 250.,
                   252., 254., 256., 258., 260., 262., 264., 266., 268.,
                   270., 272., 274., 276., 278., 280., 282., 284., 286.,
                   288., 290., 292., 294., 296., 298., 300., 302., 304.,
                   306., 308., 310., 312., 314., 316., 318., 320., 322.,
                   324., 326., 328., 330., 332., 334., 336., 338., 340.,
                   342., 344., 346., 348., 350., 352., 354., 356., 358.],
             mask=False,
       fill_value=1e+20,
            dtype=float32)

In [13]:
time = data.variables['time']
time_ = time[:]
time_units = time.units
time_calendar = time.calendar
time_dates = num2date(time_, units=time_units, calendar=time_calendar)
start_date = datetime.datetime(1958, 1, 1)
start_index = date2index(start_date, time, select='nearest')
sst_subset = data['sst'][start_index:, :, :]

In [14]:
data_ = np.array(sst_subset)
#data_[data_ == -9.96921e+36] = 0

In [15]:
for date in time_dates:
    print(date)

1958-01-01 00:00:00
1958-02-01 00:00:00
1958-03-01 00:00:00
1958-04-01 00:00:00
1958-05-01 00:00:00
1958-06-01 00:00:00
1958-07-01 00:00:00
1958-08-01 00:00:00
1958-09-01 00:00:00
1958-10-01 00:00:00
1958-11-01 00:00:00
1958-12-01 00:00:00
1959-01-01 00:00:00
1959-02-01 00:00:00
1959-03-01 00:00:00
1959-04-01 00:00:00
1959-05-01 00:00:00
1959-06-01 00:00:00
1959-07-01 00:00:00
1959-08-01 00:00:00
1959-09-01 00:00:00
1959-10-01 00:00:00
1959-11-01 00:00:00
1959-12-01 00:00:00
1960-01-01 00:00:00
1960-02-01 00:00:00
1960-03-01 00:00:00
1960-04-01 00:00:00
1960-05-01 00:00:00
1960-06-01 00:00:00
1960-07-01 00:00:00
1960-08-01 00:00:00
1960-09-01 00:00:00
1960-10-01 00:00:00
1960-11-01 00:00:00
1960-12-01 00:00:00
1961-01-01 00:00:00
1961-02-01 00:00:00
1961-03-01 00:00:00
1961-04-01 00:00:00
1961-05-01 00:00:00
1961-06-01 00:00:00
1961-07-01 00:00:00
1961-08-01 00:00:00
1961-09-01 00:00:00
1961-10-01 00:00:00
1961-11-01 00:00:00
1961-12-01 00:00:00
1962-01-01 00:00:00
1962-02-01 00:00:00
1962-03-01 00:00:00
1962-04-01 00:00:00
1962-05-01 00:00:00
1962-06-01 00:00:00
1962-07-01 00:00:00
1962-08-01 00:00:00
1962-09-01 00:00:00
1962-10-01 00:00:00
1962-11-01 00:00:00
1962-12-01 00:00:00
1963-01-01 00:00:00
1963-02-01 00:00:00
1963-03-01 00:00:00
1963-04-01 00:00:00
1963-05-01 00:00:00
1963-06-01 00:00:00
1963-07-01 00:00:00
1963-08-01 00:00:00
1963-09-01 00:00:00
1963-10-01 00:00:00
1963-11-01 00:00:00
1963-12-01 00:00:00
1964-01-01 00:00:00
1964-02-01 00:00:00
1964-03-01 00:00:00
1964-04-01 00:00:00
1964-05-01 00:00:00
1964-06-01 00:00:00
1964-07-01 00:00:00
1964-08-01 00:00:00
1964-09-01 00:00:00
1964-10-01 00:00:00
1964-11-01 00:00:00
1964-12-01 00:00:00
1965-01-01 00:00:00
1965-02-01 00:00:00
1965-03-01 00:00:00
1965-04-01 00:00:00
1965-05-01 00:00:00
1965-06-01 00:00:00
1965-07-01 00:00:00
1965-08-01 00:00:00
1965-09-01 00:00:00
1965-10-01 00:00:00
1965-11-01 00:00:00
1965-12-01 00:00:00
1966-01-01 00:00:00
1966-02-01 00:00:00
1966-03-01 00:00:00
1966-04-01 00:00:00
1966-05-01 00:00:00
1966-06-01 00:00:00
1966-07-01 00:00:00
1966-08-01 00:00:00
1966-09-01 00:00:00
1966-10-01 00:00:00
1966-11-01 00:00:00
1966-12-01 00:00:00
1967-01-01 00:00:00
1967-02-01 00:00:00
1967-03-01 00:00:00
1967-04-01 00:00:00
1967-05-01 00:00:00
1967-06-01 00:00:00
1967-07-01 00:00:00
1967-08-01 00:00:00
1967-09-01 00:00:00
1967-10-01 00:00:00
1967-11-01 00:00:00
1967-12-01 00:00:00
1968-01-01 00:00:00
1968-02-01 00:00:00
1968-03-01 00:00:00
1968-04-01 00:00:00
1968-05-01 00:00:00
1968-06-01 00:00:00
1968-07-01 00:00:00
1968-08-01 00:00:00
1968-09-01 00:00:00
1968-10-01 00:00:00
1968-11-01 00:00:00
1968-12-01 00:00:00
1969-01-01 00:00:00
1969-02-01 00:00:00
1969-03-01 00:00:00
1969-04-01 00:00:00
1969-05-01 00:00:00
1969-06-01 00:00:00
1969-07-01 00:00:00
1969-08-01 00:00:00
1969-09-01 00:00:00
1969-10-01 00:00:00
1969-11-01 00:00:00
1969-12-01 00:00:00
1970-01-01 00:00:00
1970-02-01 00:00:00
1970-03-01 00:00:00
1970-04-01 00:00:00
1970-05-01 00:00:00
1970-06-01 00:00:00
1970-07-01 00:00:00
1970-08-01 00:00:00
1970-09-01 00:00:00
1970-10-01 00:00:00
1970-11-01 00:00:00
1970-12-01 00:00:00
1971-01-01 00:00:00
1971-02-01 00:00:00
1971-03-01 00:00:00
1971-04-01 00:00:00
1971-05-01 00:00:00
1971-06-01 00:00:00
1971-07-01 00:00:00
1971-08-01 00:00:00
1971-09-01 00:00:00
1971-10-01 00:00:00
1971-11-01 00:00:00
1971-12-01 00:00:00
1972-01-01 00:00:00
1972-02-01 00:00:00
1972-03-01 00:00:00
1972-04-01 00:00:00
1972-05-01 00:00:00
1972-06-01 00:00:00
1972-07-01 00:00:00
1972-08-01 00:00:00
1972-09-01 00:00:00
1972-10-01 00:00:00
1972-11-01 00:00:00
1972-12-01 00:00:00
1973-01-01 00:00:00
1973-02-01 00:00:00
1973-03-01 00:00:00
1973-04-01 00:00:00
1973-05-01 00:00:00
1973-06-01 00:00:00
1973-07-01 00:00:00
1973-08-01 00:00:00
1973-09-01 00:00:00
1973-10-01 00:00:00
1973-11-01 00:00:00
1973-12-01 00:00:00
1974-01-01 00:00:00
1974-02-01 00:00:00
1974-03-01 00:00:00
1974-04-01 00:00:00
1974-05-01 00:00:00
1974-06-01 00:00:00
1974-07-01 00:00:00
1974-08-01 00:00:00
1974-09-01 00:00:00
1974-10-01 00:00:00
1974-11-01 00:00:00
1974-12-01 00:00:00
1975-01-01 00:00:00
1975-02-01 00:00:00
1975-03-01 00:00:00
1975-04-01 00:00:00
1975-05-01 00:00:00
1975-06-01 00:00:00
1975-07-01 00:00:00
1975-08-01 00:00:00
1975-09-01 00:00:00
1975-10-01 00:00:00
1975-11-01 00:00:00
1975-12-01 00:00:00
1976-01-01 00:00:00
1976-02-01 00:00:00
1976-03-01 00:00:00
1976-04-01 00:00:00
1976-05-01 00:00:00
1976-06-01 00:00:00
1976-07-01 00:00:00
1976-08-01 00:00:00
1976-09-01 00:00:00
1976-10-01 00:00:00
1976-11-01 00:00:00
1976-12-01 00:00:00
1977-01-01 00:00:00
1977-02-01 00:00:00
1977-03-01 00:00:00
1977-04-01 00:00:00
1977-05-01 00:00:00
1977-06-01 00:00:00
1977-07-01 00:00:00
1977-08-01 00:00:00
1977-09-01 00:00:00
1977-10-01 00:00:00
1977-11-01 00:00:00
1977-12-01 00:00:00
1978-01-01 00:00:00
1978-02-01 00:00:00
1978-03-01 00:00:00
1978-04-01 00:00:00
1978-05-01 00:00:00
1978-06-01 00:00:00
1978-07-01 00:00:00
1978-08-01 00:00:00
1978-09-01 00:00:00
1978-10-01 00:00:00
1978-11-01 00:00:00
1978-12-01 00:00:00
1979-01-01 00:00:00
1979-02-01 00:00:00
1979-03-01 00:00:00
1979-04-01 00:00:00
1979-05-01 00:00:00
1979-06-01 00:00:00
1979-07-01 00:00:00
1979-08-01 00:00:00
1979-09-01 00:00:00
1979-10-01 00:00:00
1979-11-01 00:00:00
1979-12-01 00:00:00
1980-01-01 00:00:00
1980-02-01 00:00:00
1980-03-01 00:00:00
1980-04-01 00:00:00
1980-05-01 00:00:00
1980-06-01 00:00:00
1980-07-01 00:00:00
1980-08-01 00:00:00
1980-09-01 00:00:00
1980-10-01 00:00:00
1980-11-01 00:00:00
1980-12-01 00:00:00
1981-01-01 00:00:00
1981-02-01 00:00:00
1981-03-01 00:00:00
1981-04-01 00:00:00
1981-05-01 00:00:00
1981-06-01 00:00:00
1981-07-01 00:00:00
1981-08-01 00:00:00
1981-09-01 00:00:00
1981-10-01 00:00:00
1981-11-01 00:00:00
1981-12-01 00:00:00
1982-01-01 00:00:00
1982-02-01 00:00:00
1982-03-01 00:00:00
1982-04-01 00:00:00
1982-05-01 00:00:00
1982-06-01 00:00:00
1982-07-01 00:00:00
1982-08-01 00:00:00
1982-09-01 00:00:00
1982-10-01 00:00:00
1982-11-01 00:00:00
1982-12-01 00:00:00
1983-01-01 00:00:00
1983-02-01 00:00:00
1983-03-01 00:00:00
1983-04-01 00:00:00
1983-05-01 00:00:00
1983-06-01 00:00:00
1983-07-01 00:00:00
1983-08-01 00:00:00
1983-09-01 00:00:00
1983-10-01 00:00:00
1983-11-01 00:00:00
1983-12-01 00:00:00
1984-01-01 00:00:00
1984-02-01 00:00:00
1984-03-01 00:00:00
1984-04-01 00:00:00
1984-05-01 00:00:00
1984-06-01 00:00:00
1984-07-01 00:00:00
1984-08-01 00:00:00
1984-09-01 00:00:00
1984-10-01 00:00:00
1984-11-01 00:00:00
1984-12-01 00:00:00
1985-01-01 00:00:00
1985-02-01 00:00:00
1985-03-01 00:00:00
1985-04-01 00:00:00
1985-05-01 00:00:00
1985-06-01 00:00:00
1985-07-01 00:00:00
1985-08-01 00:00:00
1985-09-01 00:00:00
1985-10-01 00:00:00
1985-11-01 00:00:00
1985-12-01 00:00:00
1986-01-01 00:00:00
1986-02-01 00:00:00
1986-03-01 00:00:00
1986-04-01 00:00:00
1986-05-01 00:00:00
1986-06-01 00:00:00
1986-07-01 00:00:00
1986-08-01 00:00:00
1986-09-01 00:00:00
1986-10-01 00:00:00
1986-11-01 00:00:00
1986-12-01 00:00:00
1987-01-01 00:00:00
1987-02-01 00:00:00
1987-03-01 00:00:00
1987-04-01 00:00:00
1987-05-01 00:00:00
1987-06-01 00:00:00
1987-07-01 00:00:00
1987-08-01 00:00:00
1987-09-01 00:00:00
1987-10-01 00:00:00
1987-11-01 00:00:00
1987-12-01 00:00:00
1988-01-01 00:00:00
1988-02-01 00:00:00
1988-03-01 00:00:00
1988-04-01 00:00:00
1988-05-01 00:00:00
1988-06-01 00:00:00
1988-07-01 00:00:00
1988-08-01 00:00:00
1988-09-01 00:00:00
1988-10-01 00:00:00
1988-11-01 00:00:00
1988-12-01 00:00:00
1989-01-01 00:00:00
1989-02-01 00:00:00
1989-03-01 00:00:00
1989-04-01 00:00:00
1989-05-01 00:00:00
1989-06-01 00:00:00
1989-07-01 00:00:00
1989-08-01 00:00:00
1989-09-01 00:00:00
1989-10-01 00:00:00
1989-11-01 00:00:00
1989-12-01 00:00:00
1990-01-01 00:00:00
1990-02-01 00:00:00
1990-03-01 00:00:00
1990-04-01 00:00:00
1990-05-01 00:00:00
1990-06-01 00:00:00
1990-07-01 00:00:00
1990-08-01 00:00:00
1990-09-01 00:00:00
1990-10-01 00:00:00
1990-11-01 00:00:00
1990-12-01 00:00:00
1991-01-01 00:00:00
1991-02-01 00:00:00
1991-03-01 00:00:00
1991-04-01 00:00:00
1991-05-01 00:00:00
1991-06-01 00:00:00
1991-07-01 00:00:00
1991-08-01 00:00:00
1991-09-01 00:00:00
1991-10-01 00:00:00
1991-11-01 00:00:00
1991-12-01 00:00:00
1992-01-01 00:00:00
1992-02-01 00:00:00
1992-03-01 00:00:00
1992-04-01 00:00:00
1992-05-01 00:00:00
1992-06-01 00:00:00
1992-07-01 00:00:00
1992-08-01 00:00:00
1992-09-01 00:00:00
1992-10-01 00:00:00
1992-11-01 00:00:00
1992-12-01 00:00:00
1993-01-01 00:00:00
1993-02-01 00:00:00
1993-03-01 00:00:00
1993-04-01 00:00:00
1993-05-01 00:00:00
1993-06-01 00:00:00
1993-07-01 00:00:00
1993-08-01 00:00:00
1993-09-01 00:00:00
1993-10-01 00:00:00
1993-11-01 00:00:00
1993-12-01 00:00:00
1994-01-01 00:00:00
1994-02-01 00:00:00
1994-03-01 00:00:00
1994-04-01 00:00:00
1994-05-01 00:00:00
1994-06-01 00:00:00
1994-07-01 00:00:00
1994-08-01 00:00:00
1994-09-01 00:00:00
1994-10-01 00:00:00
1994-11-01 00:00:00
1994-12-01 00:00:00
1995-01-01 00:00:00
1995-02-01 00:00:00
1995-03-01 00:00:00
1995-04-01 00:00:00
1995-05-01 00:00:00
1995-06-01 00:00:00
1995-07-01 00:00:00
1995-08-01 00:00:00
1995-09-01 00:00:00
1995-10-01 00:00:00
1995-11-01 00:00:00
1995-12-01 00:00:00
1996-01-01 00:00:00
1996-02-01 00:00:00
1996-03-01 00:00:00
1996-04-01 00:00:00
1996-05-01 00:00:00
1996-06-01 00:00:00
1996-07-01 00:00:00
1996-08-01 00:00:00
1996-09-01 00:00:00
1996-10-01 00:00:00
1996-11-01 00:00:00
1996-12-01 00:00:00
1997-01-01 00:00:00
1997-02-01 00:00:00
1997-03-01 00:00:00
1997-04-01 00:00:00
1997-05-01 00:00:00
1997-06-01 00:00:00
1997-07-01 00:00:00
1997-08-01 00:00:00
1997-09-01 00:00:00
1997-10-01 00:00:00
1997-11-01 00:00:00
1997-12-01 00:00:00
1998-01-01 00:00:00
1998-02-01 00:00:00
1998-03-01 00:00:00
1998-04-01 00:00:00
1998-05-01 00:00:00
1998-06-01 00:00:00
1998-07-01 00:00:00
1998-08-01 00:00:00
1998-09-01 00:00:00
1998-10-01 00:00:00
1998-11-01 00:00:00
1998-12-01 00:00:00
1999-01-01 00:00:00
1999-02-01 00:00:00
1999-03-01 00:00:00
1999-04-01 00:00:00
1999-05-01 00:00:00
1999-06-01 00:00:00
1999-07-01 00:00:00
1999-08-01 00:00:00
1999-09-01 00:00:00
1999-10-01 00:00:00
1999-11-01 00:00:00
1999-12-01 00:00:00
2000-01-01 00:00:00
2000-02-01 00:00:00
2000-03-01 00:00:00
2000-04-01 00:00:00
2000-05-01 00:00:00
2000-06-01 00:00:00
2000-07-01 00:00:00
2000-08-01 00:00:00
2000-09-01 00:00:00
2000-10-01 00:00:00
2000-11-01 00:00:00
2000-12-01 00:00:00
2001-01-01 00:00:00
2001-02-01 00:00:00
2001-03-01 00:00:00
2001-04-01 00:00:00
2001-05-01 00:00:00
2001-06-01 00:00:00
2001-07-01 00:00:00
2001-08-01 00:00:00
2001-09-01 00:00:00
2001-10-01 00:00:00
2001-11-01 00:00:00
2001-12-01 00:00:00
2002-01-01 00:00:00
2002-02-01 00:00:00
2002-03-01 00:00:00
2002-04-01 00:00:00
2002-05-01 00:00:00
2002-06-01 00:00:00
2002-07-01 00:00:00
2002-08-01 00:00:00
2002-09-01 00:00:00
2002-10-01 00:00:00
2002-11-01 00:00:00
2002-12-01 00:00:00
2003-01-01 00:00:00
2003-02-01 00:00:00
2003-03-01 00:00:00
2003-04-01 00:00:00
2003-05-01 00:00:00
2003-06-01 00:00:00
2003-07-01 00:00:00
2003-08-01 00:00:00
2003-09-01 00:00:00
2003-10-01 00:00:00
2003-11-01 00:00:00
2003-12-01 00:00:00
2004-01-01 00:00:00
2004-02-01 00:00:00
2004-03-01 00:00:00
2004-04-01 00:00:00
2004-05-01 00:00:00
2004-06-01 00:00:00
2004-07-01 00:00:00
2004-08-01 00:00:00
2004-09-01 00:00:00
2004-10-01 00:00:00
2004-11-01 00:00:00
2004-12-01 00:00:00
2005-01-01 00:00:00
2005-02-01 00:00:00
2005-03-01 00:00:00
2005-04-01 00:00:00
2005-05-01 00:00:00
2005-06-01 00:00:00
2005-07-01 00:00:00
2005-08-01 00:00:00
2005-09-01 00:00:00
2005-10-01 00:00:00
2005-11-01 00:00:00
2005-12-01 00:00:00
2006-01-01 00:00:00
2006-02-01 00:00:00
2006-03-01 00:00:00
2006-04-01 00:00:00
2006-05-01 00:00:00
2006-06-01 00:00:00
2006-07-01 00:00:00
2006-08-01 00:00:00
2006-09-01 00:00:00
2006-10-01 00:00:00
2006-11-01 00:00:00
2006-12-01 00:00:00
2007-01-01 00:00:00
2007-02-01 00:00:00
2007-03-01 00:00:00
2007-04-01 00:00:00
2007-05-01 00:00:00
2007-06-01 00:00:00
2007-07-01 00:00:00
2007-08-01 00:00:00
2007-09-01 00:00:00
2007-10-01 00:00:00
2007-11-01 00:00:00
2007-12-01 00:00:00
2008-01-01 00:00:00
2008-02-01 00:00:00
2008-03-01 00:00:00
2008-04-01 00:00:00
2008-05-01 00:00:00
2008-06-01 00:00:00
2008-07-01 00:00:00
2008-08-01 00:00:00
2008-09-01 00:00:00
2008-10-01 00:00:00
2008-11-01 00:00:00
2008-12-01 00:00:00
2009-01-01 00:00:00
2009-02-01 00:00:00
2009-03-01 00:00:00
2009-04-01 00:00:00
2009-05-01 00:00:00
2009-06-01 00:00:00
2009-07-01 00:00:00
2009-08-01 00:00:00
2009-09-01 00:00:00
2009-10-01 00:00:00
2009-11-01 00:00:00
2009-12-01 00:00:00
2010-01-01 00:00:00
2010-02-01 00:00:00
2010-03-01 00:00:00
2010-04-01 00:00:00
2010-05-01 00:00:00
2010-06-01 00:00:00
2010-07-01 00:00:00
2010-08-01 00:00:00
2010-09-01 00:00:00
2010-10-01 00:00:00
2010-11-01 00:00:00
2010-12-01 00:00:00
2011-01-01 00:00:00
2011-02-01 00:00:00
2011-03-01 00:00:00
2011-04-01 00:00:00
2011-05-01 00:00:00
2011-06-01 00:00:00
2011-07-01 00:00:00
2011-08-01 00:00:00
2011-09-01 00:00:00
2011-10-01 00:00:00
2011-11-01 00:00:00
2011-12-01 00:00:00
2012-01-01 00:00:00
2012-02-01 00:00:00
2012-03-01 00:00:00
2012-04-01 00:00:00
2012-05-01 00:00:00
2012-06-01 00:00:00
2012-07-01 00:00:00
2012-08-01 00:00:00
2012-09-01 00:00:00
2012-10-01 00:00:00
2012-11-01 00:00:00
2012-12-01 00:00:00
2013-01-01 00:00:00
2013-02-01 00:00:00
2013-03-01 00:00:00
2013-04-01 00:00:00
2013-05-01 00:00:00
2013-06-01 00:00:00
2013-07-01 00:00:00
2013-08-01 00:00:00
2013-09-01 00:00:00
2013-10-01 00:00:00
2013-11-01 00:00:00
2013-12-01 00:00:00
2014-01-01 00:00:00
2014-02-01 00:00:00
2014-03-01 00:00:00
2014-04-01 00:00:00
2014-05-01 00:00:00
2014-06-01 00:00:00
2014-07-01 00:00:00
2014-08-01 00:00:00
2014-09-01 00:00:00
2014-10-01 00:00:00
2014-11-01 00:00:00
2014-12-01 00:00:00
2015-01-01 00:00:00
2015-02-01 00:00:00
2015-03-01 00:00:00
2015-04-01 00:00:00
2015-05-01 00:00:00
2015-06-01 00:00:00
2015-07-01 00:00:00
2015-08-01 00:00:00
2015-09-01 00:00:00
2015-10-01 00:00:00
2015-11-01 00:00:00
2015-12-01 00:00:00
2016-01-01 00:00:00
2016-02-01 00:00:00
2016-03-01 00:00:00
2016-04-01 00:00:00
2016-05-01 00:00:00
2016-06-01 00:00:00
2016-07-01 00:00:00
2016-08-01 00:00:00
2016-09-01 00:00:00
2016-10-01 00:00:00
2016-11-01 00:00:00
2016-12-01 00:00:00

In [16]:
data_

array([[[-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        ...,
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36]],

       [[-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        ...,
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36]],

       [[-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        ...,
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36]],

       ...,

       [[-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        [-1.80000e+00, -1.80000e+00, -1.80000e+00, ..., -1.80000e+00,
         -1.80000e+00, -1.80000e+00],
        ...,
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36]],

       [[-1.75000e+00, -1.75000e+00, -1.74000e+00, ..., -1.76000e+00,
         -1.76000e+00, -1.75000e+00],
        [-1.69000e+00, -1.69000e+00, -1.67000e+00, ..., -1.76000e+00,
         -1.73000e+00, -1.71000e+00],
        [-1.73000e+00, -1.69000e+00, -1.67000e+00, ..., -1.80000e+00,
         -1.78000e+00, -1.76000e+00],
        ...,
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36]],

       [[-1.78000e+00, -1.77000e+00, -1.77000e+00, ..., -1.78000e+00,
         -1.78000e+00, -1.78000e+00],
        [-1.75000e+00, -1.75000e+00, -1.75000e+00, ..., -1.77000e+00,
         -1.76000e+00, -1.75000e+00],
        [-1.74000e+00, -1.73000e+00, -1.73000e+00, ..., -1.78000e+00,
         -1.76000e+00, -1.75000e+00],
        ...,
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36],
        [-9.96921e+36, -9.96921e+36, -9.96921e+36, ..., -9.96921e+36,
         -9.96921e+36, -9.96921e+36]]], dtype=float32)

In [17]:
number_of_zeros_sst = np.count_nonzero( data_ == np.min(data_))
number_of_zeros_sst

3562656

In [38]:
np.min(data_)

nan

In [18]:
zero_indices = np.where(data_ == np.min(data_))

In [19]:
zero_indices

(array([  0,   0,   0, ..., 707, 707, 707], dtype=int64),
 array([ 3,  3,  3, ..., 88, 88, 88], dtype=int64),
 array([138, 139, 140, ..., 177, 178, 179], dtype=int64))

In [20]:
data_[zero_indices] = np.nan

In [21]:
np.max(data_)

nan

In [22]:
number_of_zeros_ = np.count_nonzero( data_ == 0)

In [23]:
number_of_zeros_

2360

In [24]:
data_.shape

(708, 89, 180)

In [25]:
len(data_)

708

In [26]:
num_years = data_.shape[0] // 12
num_months = data_.shape[0] // num_years

In [27]:
num_years

59

In [28]:
num_months

12

In [29]:
data_reshaped = np.reshape(data_, (len(data_) // 12, 12, 89, 180))

In [30]:
import numpy as np

def average_lat_lon(data):
    """Averages the latitude and longitude coordinates in a multidimensional array.

    Args:
        data: A multidimensional array with dimensions (years, months, lat, lon).

    Returns:
        A multidimensional array with dimensions (years, months, 18, 18).
    """

    lat_avg_size = data.shape[2] // 18
    lon_avg_size = data.shape[3] // 18

    # Calculate the new shape for latitude and longitude
    new_lat_shape = 18
    new_lon_shape = 18

    # Create an empty array to store the averaged data
    averaged_data = np.zeros((data.shape[0], data.shape[1], new_lat_shape, new_lon_shape))

    # Iterate over latitude and longitude ranges
    for lat_idx in range(new_lat_shape):
        lat_range_start = lat_idx * lat_avg_size
        lat_range_end = (lat_idx + 1) * lat_avg_size

        for lon_idx in range(new_lon_shape):
            lon_range_start = lon_idx * lon_avg_size
            lon_range_end = (lon_idx + 1) * lon_avg_size

            # Select the subset of data for averaging
            subset = data[:, :, lat_range_start:lat_range_end, lon_range_start:lon_range_end]

            # Calculate the average along the latitude and longitude dimensions
            averaged_value = np.nanmean(subset, axis=(2, 3))

            # Store the averaged data
            averaged_data[:, :, lat_idx, lon_idx] = averaged_value

    return averaged_data

In [31]:
 avg = average_lat_lon(data_reshaped)

C:\Users\navee\AppData\Local\Temp\ipykernel_11076\2295201832.py:36: RuntimeWarning: Mean of empty slice
  averaged_value = np.nanmean(subset, axis=(2, 3))

In [32]:
avg.shape

(59, 12, 18, 18)

In [33]:
avg[1,1,:,1]

array([-1.79999995, -0.29324996,  2.38894725,  1.14916658,  3.05499983,
        7.6257143 , 15.69038486, 18.41889   , 24.05249977,         nan,
               nan,         nan,         nan, 28.15999794, 26.24250031,
       21.79999924, 12.87725067,  3.18274999])

In [34]:
final= np.reshape(avg, (len(data_) // 12, 12, 324))

In [35]:
final.shape

(59, 12, 324)

In [36]:
number_of_zeros_final = np.count_nonzero( final == 0)
number_of_zeros_final

2

In [37]:
new_data

NameError: name 'new_data' is not defined

In [ ]:
number_of_zeros_new = np.count_nonzero(new_data == 0)
number_of_zeros_new

In [ ]:
number_of_zeros_avg = np.count_nonzero(np.isnan(final))

In [ ]:
number_of_zeros_avg

In [ ]:
np.max(final)

In [ ]:
np.min(final)

In [ ]:
ff= final.reshape(324,708)
ff.shape

In [ ]:
import numpy as np

def calculate_monthly_anomaliess(data):
    """Calculate monthly anomalies and mean for a given dataset.

    Args:
        data: A multidimensional array with dimensions (years, months, latlon).

    Returns:
        monthly_anomalies: An array with monthly anomalies of the same shape as the input data.
        monthly_mean: A multidimensional array with dimensions (months, latlon) representing the mean for each month.
    """


    anomalies = np.zeros((59,12,324))
    for i in range(data.shape[2]):
        for j in range(data.shape[1]):
            month = data[:, j, i]
            monthly_mean = np.mean(month)
            anomalies[:, j, i] = month - monthly_mean
    return anomalies

def min_max_normalize(data):
    """Perform min-max normalization on the data.

    Args:
        data: A numpy array.

    Returns:
        The normalized data with values ranging from -1 to 1.
    """
    min_val = np.min(data)
    max_val = np.max(data)
    normalized_data = (data - min_val) / (max_val - min_val)  # Normalize to the range [0, 1]
    normalized_data = 2 * normalized_data - 1  # Scale to the range [-1, 1]

    return normalized_data

In [ ]:
    
import numpy as np

def anomaliess(data):
    anomaliess = np.zeros((data.shape[0], data.shape[1], data.shape[2]))

    for i in range(data.shape[2]):
        for j in range(data.shape[1]):
            month = data[:, j, i]
            monthly_mean = np.mean(month)
            anomaliess[:, j, i] = month - monthly_mean

    return anomaliess

In [ ]:
anomalies = calculate_monthly_anomaliess(final)

In [ ]:
anomalies

In [ ]:
normalized_anomalies = min_max_normalize(anomalies)
normalized_anomalies

In [ ]:
normalized_anomalies.shape

In [ ]:
np.max(np.abs(anomalies))

In [ ]:
num_positive_values = np.sum(anomalies > 0)

# Find the number of negative values
num_negative_values = np.sum(anomalies < 0)

# Find the number of zero values (optional)
num_zero_values = np.sum(anomalies == 0)

print("Number of positive values:", num_positive_values)
print("Number of negative values:", num_negative_values)
print("Number of zero values:", num_zero_values)

In [ ]:
anomalies.shape

In [ ]:
input_dim = 324
hidden_dim = 65
input_layer = Input(shape = (input_dim,))
hidden_layer = Dense(hidden_dim,activation='tanh')(input_layer)
output_layer = Dense(input_dim,activation='linear')(hidden_layer)

In [ ]:
input_data = normalized_anomalies.reshape(-1, input_dim)
input_data.shape

In [ ]:
autoencoder = Model(inputs=input_layer, outputs=output_layer)

In [ ]:
autoencoder.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
autoencoder.fit(input_data, input_data, epochs=10
                , batch_size=8)

In [ ]:
encoded_data = autoencoder.predict(input_data)

In [ ]:
encoded_data.shape

In [ ]:
decoded_data = autoencoder.predict(encoded_data)

In [ ]:
decoded_data.shape

In [ ]:
weights = autoencoder.get_weights()[0]  # Get the weights of the first layer (between input and hidden)

In [ ]:
weights.shape

In [ ]:
import matplotlib.pyplot as plt
# Calculate the mean and standard deviation of the weights.
mean = np.mean(weights)
sigma = np.std(weights)

# Plot a histogram of the weights.
plt.hist(weights, bins=50)
plt.axvline(mean, color='red', linestyle='dashed')
plt.axvline(mean + 2*sigma, color='red')
plt.axvline(mean - 2*sigma, color='red')
plt.title('Histogram of Weights')
plt.xlabel('Weight')
plt.ylabel('Count')
plt.show()

In [ ]:
weight = weights.T
weight

In [ ]:
weight.shape

In [ ]:
def Tweights(weight):
    num = []

    for i in range(weight.shape[0]):
        weight_mean = np.mean(weight[i,:])
        weight_std = np.std(weight[i,:])
        threshold = weight_mean + 1.1* weight_std
        nodes_with_weight_above_threshold = np.sum(weight[i, :] > threshold)
        ten_percent_nodes = int(0.1 * weight.shape[1])
        if nodes_with_weight_above_threshold >= ten_percent_nodes:
            num.append(nodes_with_weight_above_threshold)
            print(i,nodes_with_weight_above_threshold,threshold)

    return num

In [ ]:
 we= Tweights(weight)

In [ ]:
len(we)

In [ ]:
pred = np.zeros((65,708))
for i in range(weight.shape[0]):
    weight_mean = np.mean(weight[i,:])
    weight_std = np.std(weight[i,:])
    threshold = weight_mean + 1.1* weight_std
    nodes_with_weight_above_threshold = np.sum(weight[i, :] > threshold)
    ten_percent_nodes = int(0.1 * weight.shape[1])
    if nodes_with_weight_above_threshold >= ten_percent_nodes:
        for h in range(input_data.shape[0]): 
            pred_i = 0
            for j in range(weight.shape[1]):
                weight_value = weight[i,j]
                if weight_value > threshold:
                    pp = np.sum(weight_value*input_data[h,j])
                    pred_i += pp
                    pred[i,h] = pred_i
                

print(pred)

In [ ]:
number_of_zeros = np.count_nonzero( pred == 0)

In [ ]:
number_of_zeros

In [ ]:
pred.shape

In [ ]:
predd = pred[0,:].reshape(59,12)
predd

In [ ]:
df = pd.read_csv("enso_index.csv")
df

In [ ]:
df['avg'] = df[['jun', 'jul', 'aug', 'sep']].mean(axis=1)

In [ ]:
df

In [ ]:
predd = pred[1,:].reshape(59,12)
        # Create year and month ranges
years = pd.date_range(start='1958', end='2016', freq='YS').year
months = pd.date_range(start='1975-01', periods=12, freq='MS').strftime('%B')
        # Create the DataFrame
dff = pd.DataFrame(predd, index=years, columns=months)
dff = dff.reset_index()
dff['enso_avg'] = df['avg'].copy()

In [ ]:
dff['June'][0]

In [ ]:
dff

In [ ]:
dff.loc[-1] = [1957,0,0,0,0,0, dff['June'][0],dff['July'][0],dff['August'][0], dff['September'][0],dff['October'][0],dff['November'][0],dff['December'][0],dff['enso_avg'][0]]

dff.index = dff.index + 1  # shifting index
dff = dff.sort_index()

In [ ]:
dff

In [ ]:
dff = dff.drop('index',axis=1)

In [ ]:
def potential_predictors_new(data):
    for i in range(65):
        pred_pres = data[i,:].reshape(59,12)
        # Create year and month ranges
        years = pd.date_range(start='1958', end='2016', freq='YS').year
        months = pd.date_range(start='1975-01', periods=12, freq='MS').strftime('%B')
        # Create the DataFrame
        
        df_pres = pd.DataFrame(pred_pres, index=years, columns=months)
        df_pres = df_pres.reset_index()
        df_pres['enso_avg'] = df['avg'].copy()
        df_pres.loc[-1] = [1957,0,0,0,0,0, df_pres['June'][0],df_pres['July'][0],df_pres['August'][0], df_pres['September'][0],df_pres['October'][0],df_pres['November'][0],df_pres['December'][0],df_pres['enso_avg'][0]]
        df_pres.index = df_pres.index + 1  # shifting index
        df_pres = df_pres.sort_index() 
        df_pres= df_pres.drop('index',axis=1)
        df_6 = df_pres.iloc[1:, :5]
        df_6 = df_6.reset_index()
        df_12 = df_pres.iloc[0:-1, 6:12]
        df_12 = df_12.reset_index()
        df_13 = df_pres.iloc[1:, [12]]
        df_13 = df_13.reset_index()
        df_last = pd.concat([df_6, df_12, df_13], axis=1)
        df_last = df_last.drop('index',axis=1)
        correlation = df_last.corr(method='pearson')
        second_max_value = correlation['enso_avg'].sort_values(ascending=False)[1]
        negative_minimum = correlation['enso_avg'].sort_values(ascending=False)[-1]
        second_max_index = correlation['enso_avg'].sort_values(ascending=False).index[1]
        negative_min_index = correlation['enso_avg'].sort_values(ascending=False).index[-1]
        print(i,second_max_index,second_max_value,negative_min_index,negative_minimum)

In [ ]:
potential_predictors_new(pred)

In [ ]:
dff

In [ ]:
df_6 = dff.iloc[1:, :5]

In [ ]:
df_6 = df_6.reset_index()

In [ ]:
df_6

In [ ]:
df_12 = dff.iloc[0:-1, 6:12]

In [ ]:
df_12 = df_12.reset_index()

In [ ]:
df_12

In [ ]:
df_13 = dff.iloc[1:, [12]]

In [ ]:
df_13 = df_13.reset_index()

In [ ]:
df_13

In [ ]:
df_last = pd.concat([df_6, df_12, df_13], axis=1)

In [ ]:
df_last = df_last.drop('index',axis=1)

In [ ]:
df_last

In [ ]:
correlation_ = df_last.corr(method='pearson')
second_max_value_ = abs(correlation_['enso_avg'].sort_values(ascending=False)[1])
second_max_index_ = correlation_['enso_avg'].sort_values(ascending=False).index[1]
print(second_max_index_,second_max_value_)

In [ ]:
correlation_